-- =============================================================================
-- EasyOA v0.1.0 — Phase 1 基线（用户 / 会话 / 登录限制 / 系统设置 / 审计 / 安全事件）
--
-- 约定：
--   * 所有时间列使用 TIMESTAMPTZ，存储 UTC；
--   * 业务对象默认软删除（deleted_at）或状态化，不物理删除；
--   * 审计与安全事件为 Append Only：不提供 update/delete 语义。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
create table users (
  id                    bigint generated by default as identity primary key,
  username              varchar(64)  not null,
  email                 varchar(190),
  display_name          varchar(64)  not null,
  password_hash         varchar(100) not null,
  system_role           varchar(20)  not null default 'MEMBER',
  status                varchar(20)  not null default 'ACTIVE',
  avatar_url            varchar(500),
  phone                 varchar(32),
  bio                   varchar(500),
  totp_enabled          boolean      not null default false,
  totp_secret_encrypted varchar(255),
  password_changed_at   timestamptz,
  last_login_at         timestamptz,
  created_at            timestamptz  not null default now(),
  updated_at            timestamptz  not null default now(),
  version               bigint       not null default 0,
  deleted_at            timestamptz
);

-- 用户名唯一（仅对未删除用户生效），大小写不敏感
create unique index ux_users_username_active on users (lower(username)) where deleted_at is null;
create index ix_users_system_role on users (system_role) where deleted_at is null;

-- -----------------------------------------------------------------------------
-- user_sessions：数据库只保存 HMAC 签名，不保存原始 Session ID
-- -----------------------------------------------------------------------------
create table user_sessions (
  id                bigint generated by default as identity primary key,
  user_id           bigint      not null references users (id),
  session_key_hash  varchar(64) not null,
  ip_address        varchar(45),
  user_agent        varchar(400),
  created_at        timestamptz not null default now(),
  last_seen_at      timestamptz not null default now(),
  expires_at        timestamptz not null,
  revoked_at        timestamptz,
  revoked_reason    varchar(64)
);

create unique index ux_user_sessions_key_hash on user_sessions (session_key_hash);
create index ix_user_sessions_user_active on user_sessions (user_id) where revoked_at is null;
create index ix_user_sessions_expires_at on user_sessions (expires_at);

-- -----------------------------------------------------------------------------
-- login_attempts：登录失败限制与安全分析（追加写入）
-- -----------------------------------------------------------------------------
create table login_attempts (
  id             bigint generated by default as identity primary key,
  username       varchar(64) not null,
  ip_address     varchar(45),
  successful     boolean     not null,
  failure_reason varchar(64),
  created_at     timestamptz not null default now()
);

create index ix_login_attempts_username_time on login_attempts (lower(username), created_at desc);
create index ix_login_attempts_ip_time on login_attempts (ip_address, created_at desc);

-- -----------------------------------------------------------------------------
-- system_settings：单组织键值配置
-- -----------------------------------------------------------------------------
create table system_settings (
  key        varchar(80) primary key,
  value      varchar(4000) not null,
  updated_at timestamptz   not null default now(),
  updated_by bigint
);

insert into system_settings (key, value) values ('setup.completed', 'false');
insert into system_settings (key, value) values ('organization.name', 'Easy Studio');

-- -----------------------------------------------------------------------------
-- audit_logs：Append Only，永不 UPDATE / DELETE
-- actor 信息保留快照（actor_username），不依赖外键，保证历史可追溯
-- -----------------------------------------------------------------------------
create table audit_logs (
  id             bigint generated by default as identity primary key,
  actor_user_id  bigint,
  actor_username varchar(64) not null,
  action         varchar(80) not null,
  resource_type  varchar(60),
  resource_id    varchar(64),
  before_data    jsonb,
  after_data     jsonb,
  reason         varchar(500),
  ip_address     varchar(45),
  user_agent     varchar(400),
  request_id     varchar(64),
  risk_level     varchar(20) not null default 'NORMAL',
  created_at     timestamptz not null default now()
);

create index ix_audit_logs_actor_time on audit_logs (actor_user_id, created_at desc);
create index ix_audit_logs_resource on audit_logs (resource_type, resource_id);
create index ix_audit_logs_action_time on audit_logs (action, created_at desc);
create index ix_audit_logs_created_at on audit_logs (created_at desc);

-- -----------------------------------------------------------------------------
-- security_events：高危安全事件，永久追加；预留哈希链字段
-- -----------------------------------------------------------------------------
create table security_events (
  id             bigint generated by default as identity primary key,
  event_type     varchar(80)  not null,
  severity       varchar(20)  not null default 'INFO',
  description    varchar(500) not null,
  detail         jsonb,
  actor_user_id  bigint,
  actor_username varchar(64),
  ip_address     varchar(45),
  user_agent     varchar(400),
  request_id     varchar(64),
  previous_hash  varchar(128),
  entry_hash     varchar(128),
  created_at     timestamptz  not null default now()
);

create index ix_security_events_type_time on security_events (event_type, created_at desc);
create index ix_security_events_created_at on security_events (created_at desc);