-- =============================================================================
-- EasyOA v0.1.0 — Phase 2：组织架构
--
-- 设计要点：
--   * 组织树使用邻接表（parent_id），查询使用 PostgreSQL WITH RECURSIVE；
--   * 组织归属（Org Membership）与项目成员（Project Membership）彻底分离；
--   * 每个用户最多一个主部门（Partial Unique Index 在数据库层保证）；
--   * 组织单元使用归档（ARCHIVED）而不是删除，保证历史完整。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users：新增职位字段（团队页面 / 成员档案展示）
-- -----------------------------------------------------------------------------
alter table users add column job_title varchar(64);

-- -----------------------------------------------------------------------------
-- org_units：组织单元（部门 / 团队）
-- -----------------------------------------------------------------------------
create table org_units (
  id              bigint generated by default as identity primary key,
  parent_id       bigint references org_units (id) on delete cascade,
  name            varchar(80)  not null,
  type            varchar(20)  not null,                 -- DEPARTMENT | TEAM
  sort_order      integer      not null default 0,
  status          varchar(20)  not null default 'ACTIVE', -- ACTIVE | ARCHIVED
  -- 负责人被物理删除（仅测试/运维场景）时置空，绝不级联删除组织单元
  manager_user_id bigint references users (id) on delete set null,
  created_at      timestamptz  not null default now(),
  updated_at      timestamptz  not null default now(),
  version         bigint       not null default 0
);

create index ix_org_units_parent on org_units (parent_id);
create index ix_org_units_status on org_units (status);

-- 同一父节点下不允许出现同名单元（仅对未归档单元生效；根节点用 0 代表 null）
create unique index ux_org_units_parent_name_active
  on org_units (coalesce(parent_id, 0), lower(name))
  where status = 'ACTIVE';

-- -----------------------------------------------------------------------------
-- user_org_memberships：用户 N:N 组织归属
-- -----------------------------------------------------------------------------
create table user_org_memberships (
  id          bigint generated by default as identity primary key,
  user_id     bigint      not null references users (id) on delete cascade,
  org_unit_id bigint      not null references org_units (id) on delete cascade,
  is_primary  boolean     not null default false,
  joined_at   timestamptz not null default now()
);

-- 同一用户在同一组织单元下只能有一条归属
create unique index ux_user_org_memberships_unique on user_org_memberships (user_id, org_unit_id);

-- 每个用户最多一个主部门（数据库层强约束，业务层负责补足「恰好一个」）
create unique index ux_user_org_memberships_primary on user_org_memberships (user_id) where is_primary;

create index ix_user_org_memberships_org_unit on user_org_memberships (org_unit_id);