-- =============================================================================
-- EasyOA v0.1.0 — Phase 3：项目协作
--
-- 设计要点：
--   * 项目角色的唯一事实来源是 project_members（OWNER / DEPUTY_OWNER / MEMBER），
--     不在 projects 表冗余 owner 字段，避免双向不同步；
--   * 「单一 OWNER」「单一副负责人」由 Partial Unique Index 在数据库层保证；
--   * 项目不使用物理删除：结束使用归档（ARCHIVED，只读）。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- projects
-- -----------------------------------------------------------------------------
create table projects (
  id            bigint generated by default as identity primary key,
  name          varchar(120) not null,
  description   varchar(2000),
  status        varchar(20)  not null default 'DRAFT',
  progress      integer      not null default 0,   -- 0~100，Phase 3 手工维护；Phase 4 起可由任务聚合
  planned_start_at timestamptz,
  planned_end_at   timestamptz,
  archived_at   timestamptz,
  created_by    bigint references users (id) on delete set null,
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now(),
  version       bigint       not null default 0
);

create index ix_projects_status on projects (status);
create index ix_projects_created_at on projects (created_at desc);

alter table projects add constraint ck_projects_progress check (progress between 0 and 100);

-- -----------------------------------------------------------------------------
-- project_members：项目角色（系统角色与项目角色彻底分离）
-- -----------------------------------------------------------------------------
create table project_members (
  id         bigint generated by default as identity primary key,
  project_id bigint      not null references projects (id) on delete cascade,
  user_id    bigint      not null references users (id) on delete cascade,
  role       varchar(20) not null,   -- OWNER | DEPUTY_OWNER | MEMBER
  joined_at  timestamptz not null default now()
);

create unique index ux_project_members_unique on project_members (project_id, user_id);

-- 每个项目恰好/最多一个 OWNER
create unique index ux_project_members_single_owner on project_members (project_id) where role = 'OWNER';

-- 每个项目最多一个副负责人
create unique index ux_project_members_single_deputy on project_members (project_id) where role = 'DEPUTY_OWNER';

create index ix_project_members_user on project_members (user_id);
create index ix_project_members_project on project_members (project_id);