-- =============================================================================
-- EasyOA v0.1.0 — Phase 4：任务执行
--
-- 设计要点：
--   * 任务状态由项目自定义，但每个状态必须映射到系统统一类型
--     （TODO / ACTIVE / REVIEW / DONE / CLOSED），统计一律基于 system_type，
--     绝不依赖自定义状态名称；
--   * 子任务 = parent_task_id 非空的 tasks 行（v0.1.0 只允许一级，由服务层校验）；
--   * 状态、子任务、依赖都通过复合外键 (xxx_id, project_id) 锚定在同一个项目内，
--     跨项目数据在数据库层即被拒绝；
--   * 任务不做物理删除：结束使用状态（DONE / CLOSED），历史与审计保持完整；
--   * 依赖（前置任务）用独立关联表，循环检测由服务层完成。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- task_statuses：项目任务状态（系统默认模板 + 项目自定义）
-- -----------------------------------------------------------------------------
create table task_statuses (
  id          bigint generated by default as identity primary key,
  project_id  bigint      not null references projects (id) on delete cascade,
  name        varchar(40) not null,
  system_type varchar(20) not null,   -- TODO | ACTIVE | REVIEW | DONE | CLOSED
  sort_order  integer     not null default 0,
  created_at  timestamptz not null default now()
);

create unique index ux_task_statuses_project_name on task_statuses (project_id, name);
-- 复合外键锚点：保证任务的状态一定属于任务所在项目
create unique index ux_task_statuses_id_project on task_statuses (id, project_id);
create index ix_task_statuses_project on task_statuses (project_id, sort_order);

-- -----------------------------------------------------------------------------
-- tasks：任务与一级子任务
-- -----------------------------------------------------------------------------
create table tasks (
  id                  bigint generated by default as identity primary key,
  project_id          bigint       not null references projects (id) on delete cascade,
  parent_task_id      bigint,
  status_id           bigint       not null,
  title               varchar(200) not null,
  description         varchar(4000),
  priority            varchar(20)  not null default 'MEDIUM',   -- LOW | MEDIUM | HIGH | URGENT
  primary_assignee_id bigint       not null references users (id),
  deputy_assignee_id  bigint       references users (id),
  assignment_state    varchar(30)  not null default 'ACTIVE',   -- ACTIVE | PENDING_ASSIGNMENT | REJECTED
  progress_mode       varchar(20)  not null default 'MANUAL',   -- MANUAL | AUTO
  progress            integer      not null default 0,
  planned_start_at    timestamptz,
  planned_end_at      timestamptz,
  actual_start_at     timestamptz,
  completed_at        timestamptz,
  created_by          bigint       references users (id) on delete set null,
  created_at          timestamptz  not null default now(),
  updated_at          timestamptz  not null default now(),
  version             bigint       not null default 0,
  constraint fk_tasks_status foreign key (status_id, project_id) references task_statuses (id, project_id),
  constraint ck_tasks_progress check (progress between 0 and 100),
  constraint ck_tasks_not_self_parent check (parent_task_id is null or parent_task_id <> id)
);

-- 复合外键锚点：保证子任务与依赖都落在同一项目内
create unique index ux_tasks_id_project on tasks (id, project_id);

-- 自引用外键（复合）：必须在唯一索引创建之后再建立
alter table tasks add constraint fk_tasks_parent
  foreign key (parent_task_id, project_id) references tasks (id, project_id) on delete cascade;

create index ix_tasks_board on tasks (project_id, status_id);
create index ix_tasks_parent on tasks (parent_task_id);
create index ix_tasks_primary_assignee on tasks (primary_assignee_id);
create index ix_tasks_deputy_assignee on tasks (deputy_assignee_id);
create index ix_tasks_planned_end on tasks (planned_end_at);

-- -----------------------------------------------------------------------------
-- task_collaborators：协作成员 × N
-- -----------------------------------------------------------------------------
create table task_collaborators (
  id       bigint generated by default as identity primary key,
  task_id  bigint      not null references tasks (id) on delete cascade,
  user_id  bigint      not null references users (id) on delete cascade,
  added_at timestamptz not null default now()
);

create unique index ux_task_collaborators_unique on task_collaborators (task_id, user_id);
create index ix_task_collaborators_user on task_collaborators (user_id);

-- -----------------------------------------------------------------------------
-- task_dependencies：同项目内前置依赖（B depends on A）
-- -----------------------------------------------------------------------------
create table task_dependencies (
  id                 bigint generated by default as identity primary key,
  project_id         bigint      not null references projects (id) on delete cascade,
  task_id            bigint      not null,
  depends_on_task_id bigint      not null,
  created_by         bigint      references users (id) on delete set null,
  created_at         timestamptz not null default now(),
  constraint fk_task_dependencies_task foreign key (task_id, project_id)
      references tasks (id, project_id) on delete cascade,
  constraint fk_task_dependencies_depends_on foreign key (depends_on_task_id, project_id)
      references tasks (id, project_id) on delete cascade,
  constraint ck_task_dependencies_not_self check (task_id <> depends_on_task_id)
);

create unique index ux_task_dependencies_unique on task_dependencies (task_id, depends_on_task_id);
create index ix_task_dependencies_depends_on on task_dependencies (depends_on_task_id);

-- -----------------------------------------------------------------------------
-- 默认状态模板：为既有项目回填（新建项目由 TaskStatusService 初始化）
-- -----------------------------------------------------------------------------
insert into task_statuses (project_id, name, system_type, sort_order)
select p.id, t.name, t.system_type, t.sort_order
from projects p
cross join (values
    ('待处理', 'TODO',   0),
    ('进行中', 'ACTIVE', 1),
    ('待审核', 'REVIEW', 2),
    ('已完成', 'DONE',   3)
) as t(name, system_type, sort_order);