-- =============================================================================
-- EasyOA v0.1.0 — Phase 5：评论与文件
--
-- 设计要点：
--   * 评论不做物理删除：撤回（withdrawn_at）保留原始内容与完整编辑历史；
--   * 每次编辑写入 comment_versions（version_no 递增），当前内容冗余在 comments.content；
--   * @成员 独立关联表（发起时必须校验为项目成员）；
--   * 附件统一元数据表 files：resource_type + resource_id 泛化资源归属
--     （TASK / COMMENT），磁盘使用 UUID 随机存储名，禁止用户文件名作为真实路径；
--   * 附件只允许通过 GET /api/files/{fileId} 下载（认证 → 资源权限 → 文件权限 → 下载）。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- comments：任务评论与回复（一级回复）
-- -----------------------------------------------------------------------------
create table comments (
  id                bigint generated by default as identity primary key,
  task_id           bigint       not null references tasks (id) on delete cascade,
  parent_comment_id bigint       references comments (id) on delete cascade,
  author_id         bigint       not null references users (id),
  content           varchar(4000) not null,
  edited            boolean      not null default false,
  withdrawn_at      timestamptz,
  created_at        timestamptz  not null default now(),
  updated_at        timestamptz  not null default now(),
  version           bigint       not null default 0
);

create index ix_comments_task on comments (task_id, created_at desc);
create index ix_comments_parent on comments (parent_comment_id);

-- -----------------------------------------------------------------------------
-- comment_versions：编辑历史（version_no = 1 为原始内容，每次编辑 +1）
-- -----------------------------------------------------------------------------
create table comment_versions (
  id         bigint generated by default as identity primary key,
  comment_id bigint        not null references comments (id) on delete cascade,
  version_no integer       not null,
  content    varchar(4000) not null,
  editor_id  bigint        references users (id) on delete set null,
  created_at timestamptz   not null default now()
);

create unique index ux_comment_versions_unique on comment_versions (comment_id, version_no);

-- -----------------------------------------------------------------------------
-- comment_mentions：@成员
-- -----------------------------------------------------------------------------
create table comment_mentions (
  id         bigint generated by default as identity primary key,
  comment_id bigint      not null references comments (id) on delete cascade,
  user_id    bigint      not null references users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index ux_comment_mentions_unique on comment_mentions (comment_id, user_id);
create index ix_comment_mentions_user on comment_mentions (user_id);

-- -----------------------------------------------------------------------------
-- files：附件元数据（TASK / COMMENT）
-- -----------------------------------------------------------------------------
create table files (
  id            bigint generated by default as identity primary key,
  original_name varchar(255) not null,
  stored_name   varchar(120) not null,
  mime_type     varchar(150) not null,
  size          bigint       not null,
  sha256        varchar(64)  not null,
  uploader_id   bigint       not null references users (id),
  resource_type varchar(30)  not null,
  resource_id   bigint       not null,
  deleted_at    timestamptz,
  created_at    timestamptz  not null default now()
);

create unique index ux_files_stored_name on files (stored_name);
create index ix_files_resource on files (resource_type, resource_id);
create index ix_files_uploader on files (uploader_id);
create index ix_files_created on files (created_at desc);