-- =============================================================================
-- EasyOA v0.1.0 — Phase 6：审批流转
--
-- 设计要点：
--   * 模板版本化：approval_template_versions 只追加，新申请用最新版本，
--     已运行实例始终绑定发起时的版本（历史审批不受模板更新影响）；
--   * 表单与流程双快照：实例保存 form_snapshot（schema + values）与审批人快照，
--     组织变化不会自动修改运行中的审批人；
--   * 实例状态：DRAFT / PENDING / APPROVED / REJECTED / RETURNED / CANCELLED；
--   * 节点模式：ANY_ONE（任意一人通过）/ ALL（全部通过）；RETURN 后从第一个节点重新审批；
--   * 自我审批禁止：解析审批人时过滤申请人，无法解析出合法审批人则禁止提交。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- approval_templates：模板主表（version 为乐观锁，latest_version_no 指向当前版本）
-- -----------------------------------------------------------------------------
create table approval_templates (
  id                bigint generated by default as identity primary key,
  name              varchar(120)  not null,
  description       varchar(1000),
  enabled           boolean       not null default true,
  latest_version_no integer       not null default 0,
  created_by        bigint        references users (id) on delete set null,
  created_at        timestamptz   not null default now(),
  updated_at        timestamptz   not null default now(),
  version           bigint        not null default 0
);

create unique index ux_approval_templates_name on approval_templates (name);

-- -----------------------------------------------------------------------------
-- approval_template_versions：模板历史版本（只追加）
-- -----------------------------------------------------------------------------
create table approval_template_versions (
  id          bigint generated by default as identity primary key,
  template_id bigint        not null references approval_templates (id) on delete cascade,
  version_no  integer       not null,
  name        varchar(120)  not null,
  description varchar(1000),
  form_schema text          not null,   -- JSON：表单字段定义
  node_schema text          not null,   -- JSON：审批节点与审批人规则
  created_by  bigint        references users (id) on delete set null,
  created_at  timestamptz   not null default now()
);

create unique index ux_approval_template_versions on approval_template_versions (template_id, version_no);

-- -----------------------------------------------------------------------------
-- approval_instances：审批实例
-- -----------------------------------------------------------------------------
create table approval_instances (
  id                  bigint generated by default as identity primary key,
  title               varchar(200) not null,
  template_id         bigint       not null references approval_templates (id),
  template_version_id bigint       not null references approval_template_versions (id),
  template_version_no integer      not null,
  status              varchar(20)  not null,   -- DRAFT|PENDING|APPROVED|REJECTED|RETURNED|CANCELLED
  applicant_id        bigint       not null references users (id),
  form_snapshot       text         not null,   -- JSON：{ schema: [...], values: {...} }
  current_node_index  integer,
  submitted_at        timestamptz,
  finished_at         timestamptz,
  created_at          timestamptz  not null default now(),
  updated_at          timestamptz  not null default now(),
  version             bigint       not null default 0
);

create index ix_approval_instances_applicant on approval_instances (applicant_id, created_at desc);
create index ix_approval_instances_status on approval_instances (status, updated_at desc);

-- -----------------------------------------------------------------------------
-- approval_nodes：实例节点快照
-- -----------------------------------------------------------------------------
create table approval_nodes (
  id          bigint generated by default as identity primary key,
  instance_id bigint      not null references approval_instances (id) on delete cascade,
  node_index  integer     not null,
  name        varchar(120) not null,
  mode        varchar(10) not null,   -- ANY_ONE | ALL
  status      varchar(20) not null,   -- PENDING | APPROVED | REJECTED
  finished_at timestamptz,
  created_at  timestamptz not null default now()
);

create unique index ux_approval_nodes_instance_index on approval_nodes (instance_id, node_index);

-- -----------------------------------------------------------------------------
-- approval_node_approvers：审批人快照（组织变化不影响运行中的实例）
-- -----------------------------------------------------------------------------
create table approval_node_approvers (
  id                       bigint generated by default as identity primary key,
  node_id                  bigint       not null references approval_nodes (id) on delete cascade,
  user_id                  bigint       not null references users (id),
  rule_type                varchar(40)  not null,  -- 解析来源规则（审计可追踪）
  status                   varchar(20)  not null,  -- PENDING|APPROVED|REJECTED|RETURNED|TRANSFERRED_OUT
  comment                  varchar(1000),
  acted_at                 timestamptz,
  transferred_from_user_id bigint       references users (id),
  created_at               timestamptz  not null default now()
);

create unique index ux_approval_node_approvers on approval_node_approvers (node_id, user_id);
create index ix_approval_node_approvers_user on approval_node_approvers (user_id, status);

-- -----------------------------------------------------------------------------
-- approval_actions：审批历史（只追加）
-- -----------------------------------------------------------------------------
create table approval_actions (
  id          bigint generated by default as identity primary key,
  instance_id bigint       not null references approval_instances (id) on delete cascade,
  node_id     bigint       references approval_nodes (id) on delete set null,
  actor_id    bigint       not null references users (id),
  action      varchar(30)  not null,   -- SUBMIT|APPROVE|REJECT|RETURN|WITHDRAW|TRANSFER|UPDATE_FORM
  comment     varchar(1000),
  created_at  timestamptz  not null default now()
);

create index ix_approval_actions_instance on approval_actions (instance_id, created_at asc, id asc);