-- =============================================================================
-- EasyOA v0.1.0 — Phase 7：工作台（通知中心 / 全局搜索 / Activity Feed）
--
-- 设计要点：
--   * notifications 只存业务通知（任务 / 审批 / 评论 / 项目），与安全审计分离；
--   * link 列保存前端深链（点击通知直达对应任务 / 审批 / 项目，不跳回首页）；
--   * 即将截止 / 逾期由定时扫描生成，按「未读 + 同类型 + 同资源」去重；
--   * Activity Feed 不落库，由业务表（评论 / 任务 / 审批）+ 状态变更审计实时聚合。
-- =============================================================================

create table notifications (
  id            bigint generated by default as identity primary key,
  recipient_id  bigint       not null references users (id) on delete cascade,
  type          varchar(40)  not null,
  title         varchar(200) not null,
  body          varchar(500),
  link          varchar(300) not null,
  resource_type varchar(30),
  resource_id   bigint,
  actor_id      bigint       references users (id) on delete set null,
  read_at       timestamptz,
  created_at    timestamptz  not null default now()
);

create index ix_notifications_recipient on notifications (recipient_id, created_at desc);
create index ix_notifications_unread on notifications (recipient_id, read_at) where read_at is null;
create index ix_notifications_dedupe on notifications (recipient_id, type, resource_type, resource_id);